export const socialMedia = {
    post: [{
        _id: 1,
        name: "@arlenemcCoy",
        email: "arlene@example.com",
        img: "https://material-ui.com/static/images/avatar/1.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "CD01",
        surveyTitle: "लोकसभा चुनाव के बीच अवतार सिंह भड़ाना की कांग्रेस में वापसी",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 215,
        response: 500,
        gender: "male",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "Economy",
        ticketAmount: "$20",
        ticketStatus: "Pending",
        ticketCommision: "$5",
        noOfTicket: 5,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 2,
        name: "@jeromebell",
        email: "jerome@example.com",
        img: "https://material-ui.com/static/images/avatar/2.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "JBD02",
        surveyTitle: "If you could choose your own work schedule, would you?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 25,
        response: 50,
        gender: "male",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Deactive",
        ticketId: "#6548",
        ticketType: "Silver",
        ticketAmount: "$30",
        ticketStatus: "Pending",
        ticketCommision: "$8",
        noOfTicket: 7,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 3,
        name: "@jennywilson",
        email: "jennywilson@example.com",
        img: "https://material-ui.com/static/images/avatar/3.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "JCD01",
        surveyTitle: "Is there one job you’d never ever do?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 15,
        response: 30,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 4,
        name: "@jennywilson",
        email: "arlene@example.com",
        img: "https://material-ui.com/static/images/avatar/4.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "CD01",
        surveyTitle: "Is there one job you’d never ever do?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 35,
        response: 150,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 5,
        name: "@courtneyhenry",
        email: "arlene@example.com",
        img: "https://material-ui.com/static/images/avatar/5.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "MCD01",
        surveyTitle: "What’s the first thing you do after getting home from work?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 20,
        response: 55,
        gender: "male",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 6,
        name: "@eleanorpena",
        email: "elelene@example.com",
        img: "https://material-ui.com/static/images/avatar/6.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "ED01",
        surveyTitle: "Who or what inspires you in your career?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 215,
        response: 40,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    {
        _id: 7,
        name: "@kathrynmurphy",
        email: "kathryn@example.com",
        img: "https://material-ui.com/static/images/avatar/7.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "CD01",
        surveyTitle: "How do you approach taking time off from work?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 215,
        response: 500,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Deactive",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",

    },
    {
        _id: 8,
        name: "@albertflores",
        email: "albert@example.com",
        img: "https://material-ui.com/static/images/avatar/8.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "ALD01",
        surveyTitle: "What’s something an outsider wouldn’t know about your industry?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 42,
        response: 57,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",

    },
    {
        _id: 9,
        name: "@guyhawkins",
        email: "guyhawkins@example.com",
        img: "https://material-ui.com/static/images/avatar/9.jpg",
        dateTime: "2024-03-11T12:30:00.000Z",
        userId: "CD01",
        surveyTitle: "Do you have a morning routine at work? If so, what it’s like?",
        created_At: "2024-03-11T12:30:00.000Z",
        reach: 215,
        response: 500,
        gender: "female",
        ageCategory: "12 years",
        location: "lucknow",
        businessName: "sport Wear",
        status: "Active",
        ticketId: "#6548",
        ticketType: "GOld",
        ticketAmount: "$50",
        ticketStatus: "Pending",
        ticketCommision: "$15",
        noOfTicket: 8,
        categoryName: "clothing",
        subCategoryName: "t-shirt",
        subCategoryLength: 4,
        slug: "tshirt",
        attributeName: "length",
        attributeVlueName: "XL",
        attributeVlue: "42",
        brandName: "Nike",
        colorName: "red",
        colorValue: "#fffff",
    },
    ],
    pageInfo: {
        currentPage: 1,
        pageSize: 9,
        totalCount: 9,
        totalPages: 5
    }
}